import os
from detectron2.config import CfgNode as CN

def add_dataset_config(cfg):
  _C = cfg

  _C.MODEL.ROI_HEADS.NUM_OUTPUT_CLASSES = 80
  _C.MODEL.ROI_HEADS.EMBEDDINGS_PATH = ""
  _C.MODEL.ROI_HEADS.EMBEDDINGS_PATH_COCO = ""
  _C.MODEL.ROI_HEADS.LINGUAL_MATRIX_THRESHOLD = 0.05
  _C.MODEL.ROI_HEADS.MASK_NUM_CLASSES = 80

  _C.MODEL.FREEZE_LAYERS = CN()
  _C.MODEL.FREEZE_LAYERS.META_ARCH = []
  _C.MODEL.FREEZE_LAYERS.ROI_HEADS = []

  _C.DATASETS.TYPE = ""
  _C.DATASETS.VISUAL_GENOME = CN()
  _C.DATASETS.VISUAL_GENOME.IMAGES = ''
  _C.DATASETS.VISUAL_GENOME.MAPPING_DICTIONARY = ''
  _C.DATASETS.VISUAL_GENOME.IMAGE_DATA = ''
  _C.DATASETS.VISUAL_GENOME.SG_TRAIN_DATA = ''
  _C.DATASETS.VISUAL_GENOME.SG_VAL_DATA = ''
  _C.DATASETS.VISUAL_GENOME.SG_MAPPER = ''
  _C.DATASETS.VISUAL_GENOME.VG_ATTRIBUTE_H5 = ''
  _C.DATASETS.VISUAL_GENOME.TRAIN_MASKS = ""
  _C.DATASETS.VISUAL_GENOME.TEST_MASKS = ""
  _C.DATASETS.VISUAL_GENOME.VAL_MASKS = ""
  _C.DATASETS.VISUAL_GENOME.CLIPPED = False
  _C.DATASETS.VISUAL_GENOME.PER_CLASS_DATASET = False
  _C.DATASETS.VISUAL_GENOME.BGNN = False

  _C.DATASETS.ACTION_GENOME = CN()
  _C.DATASETS.ACTION_GENOME.ANNOTATIONS = ''
  _C.DATASETS.ACTION_GENOME.FILTER_EMPTY_RELATIONS = True
  _C.DATASETS.ACTION_GENOME.FILTER_DUPLICATE_RELATIONS = True
  _C.DATASETS.ACTION_GENOME.FILTER_NON_OVERLAP = True
  _C.DATASETS.ACTION_GENOME.FORMAT_VID_WISE = False
  _C.DATASETS.ACTION_GENOME.FRAMES = ''
  _C.DATASETS.ACTION_GENOME.VIDEOS = ''
  _C.DATASETS.ACTION_GENOME.NUM_VIDEOS_TRAIN = -1
  _C.DATASETS.ACTION_GENOME.NUM_VIDEOS_VAL = 400
  _C.DATASETS.ACTION_GENOME.VAL_SET_RANDOMIZED = False
  _C.DATASETS.ACTION_GENOME.BROKEN_IMAGES_LIST = "broken_images.txt"


  _C.DATASETS.MSCOCO = CN()
  _C.DATASETS.MSCOCO.ANNOTATIONS = ''
  _C.DATASETS.MSCOCO.DATAROOT = ''

  _C.DATASETS.VISUAL_GENOME.FILTER_EMPTY_RELATIONS = True
  _C.DATASETS.VISUAL_GENOME.FILTER_DUPLICATE_RELATIONS = True
  _C.DATASETS.VISUAL_GENOME.FILTER_NON_OVERLAP = True
  _C.DATASETS.VISUAL_GENOME.EXCLUDE_LEFT_RIGHT = False
  _C.DATASETS.VISUAL_GENOME.NUMBER_OF_VALIDATION_IMAGES = 5000
  _C.DATASETS.VISUAL_GENOME.BOX_SCALE = 1024
  _C.DATASETS.VISUAL_GENOME.MAX_NUM_RELATIONS = -1
  _C.DATASETS.VISUAL_GENOME.MAX_NUM_OBJECTS = -1
  _C.DATASETS.VISUAL_GENOME.UNDERSAMPLE_PARAM = 0.7
  _C.DATASETS.VISUAL_GENOME.OVERSAMPLE_PARAM = 0.07
  _C.DATASETS.VISUAL_GENOME.OVERFIT_NUM_IMAGES = 0
  _C.DATASETS.VISUAL_GENOME.OVERFIT_SEED = 42
  _C.DATASETS.VISUAL_GENOME.OVERFIT_SOURCE_SPLIT = "train"

  _C.DATASETS.SEG_DATA_DIVISOR = 1

  _C.DATASETS.TRANSFER = ('coco_train_2014',)
  _C.DATASETS.MASK_TRAIN = ('coco_train_2017',)
  _C.DATASETS.MASK_TEST = ('coco_val_2017',)

  _C.MODEL.DETR = CN()
  _C.MODEL.DETR.NUM_CLASSES = 80
  _C.MODEL.DETR.NUM_RELATION_CLASSES = 50

  # For Segmentation
  _C.MODEL.DETR.FROZEN_WEIGHTS = ''
  _C.MODEL.DETR.FREEZE = False
  _C.MODEL.DETR.SGDET_USE_GT = False

  # LOSS
  _C.MODEL.DETR.COST_CLASS = 1.0
  _C.MODEL.DETR.GIOU_WEIGHT = 2.0
  _C.MODEL.DETR.L1_WEIGHT = 5.0
  _C.MODEL.DETR.FOCAL_ALPHA = 0.25
  _C.MODEL.DETR.DEEP_SUPERVISION = True
  # Detection-only pretraining: skip relation loss, freeze relation branch
  _C.MODEL.DETR.DETECTION_ONLY = False
  _C.MODEL.DETR.FREEZE_RELATION_BRANCH = True
  _C.MODEL.DETR.DETECTION_ONLY_PERSON_LOSS_WEIGHT = 0.01
  _C.MODEL.DETR.NO_OBJECT_WEIGHT = 0.1
  _C.MODEL.DETR.PERSON_CLASS_WEIGHT = 1.0
  _C.MODEL.DETR.PERSON_SCORE_SCALE = 1.0
  _C.MODEL.DETR.PERSON_CLASS_INDEX = 0
  _C.MODEL.DETR.CLS_WEIGHT = 2.0
  _C.MODEL.DETR.COST_SELECTION = 1.0
  
  
  # RELATION LOSS
  _C.MODEL.DETR.RELATION_LOSS_WEIGHT = 1.0

  # TRANSFORMER
  _C.MODEL.DETR.NAME = 'DETR'
  _C.MODEL.DETR.CRITERION = 'SetCriterion'
  _C.MODEL.DETR.TRANSFORMER = 'Transformer'
  # Box regression loss type: "giou", "ciou", "eiou"
  _C.MODEL.DETR.BOX_LOSS_TYPE = "giou"
  # Corner loss (L1 on xyxy corners) as auxiliary regression loss
  _C.MODEL.DETR.USE_CORNER_LOSS = False
  _C.MODEL.DETR.CORNER_LOSS_WEIGHT = 1.0
  _C.MODEL.DETR.MATCHER = 'HungarianMatcher'
  _C.MODEL.DETR.POSITION_EMBEDDING = 'PositionEmbeddingSine'
  _C.MODEL.DETR.NHEADS = 8
  _C.MODEL.DETR.DROPOUT = 0.1
  _C.MODEL.DETR.DIM_FEEDFORWARD = 2048
  _C.MODEL.DETR.ENC_LAYERS = 6
  _C.MODEL.DETR.DEC_LAYERS = 6
  _C.MODEL.DETR.RELATION_DEC_LAYERS = 4
  _C.MODEL.DETR.OBJECT_DEC_LAYERS = 4
  _C.MODEL.DETR.PRE_NORM = False
  _C.MODEL.DETR.RELATION_HEAD = True
  _C.MODEL.DETR.CLASS_AGNOSTIC_NMS = True
  _C.MODEL.DETR.INTERSECTION_IOU_THRESHOLD = 0.3
  _C.MODEL.DETR.INTERSECTION_IOU_LAMBDA = 1.0
  _C.MODEL.DETR.INTERSECTION_LOSS = False
  _C.MODEL.DETR.NO_REL_WEIGHT = 0.1
  _C.MODEL.DETR.LATER_NMS_THRESHOLD = 0.3
  _C.MODEL.DETR.USE_FREQ_BIAS = True
  _C.MODEL.DETR.NUM_FEATURE_LEVELS = 4
  _C.MODEL.DETR.WITH_BOX_REFINE = False
  _C.MODEL.DETR.TWO_STAGE = False
  _C.MODEL.DETR.TWO_STAGE_NUM_PROPOSALS = 300
  _C.MODEL.DETR.REWEIGHT_RELATIONS = False
  _C.MODEL.DETR.REWEIGHT_USE_LOG = True
  _C.MODEL.DETR.REWEIGHT_REL_EOS_COEF = 0.1
  _C.MODEL.DETR.NEGATIVE_RELATION_FRACTION = 3.0
  _C.MODEL.DETR.MAX_RELATION_PAIRS = 16
  _C.MODEL.DETR.NMS_WEIGHT = 0.2
  _C.MODEL.DETR.BETA = 1000
  _C.MODEL.DETR.MATCHER_TOPK = 1
  _C.MODEL.DETR.OVERSAMPLE_PARAM = 0.07
  _C.MODEL.DETR.UNDERSAMPLE_PARAM = 1.0
  _C.MODEL.DETR.FREEZE_LAYERS = []
  _C.MODEL.DETR.TEST_INDEX = -1
  _C.MODEL.DETR.LOAD_HEAD_ONLY = False
  _C.MODEL.DETR.LOAD_FULL_WEIGHTS = False  # True=用 HEAD_WEIGHTS 作为 MODEL.WEIGHTS 全量加载
  _C.MODEL.DETR.LOAD_CLASS_HEAD = False  # 仅 LOAD_HEAD_ONLY 时生效：True=加载 class_embed，False=跳过并重建
  _C.MODEL.DETR.HEAD_WEIGHTS = ""
  # 当使用 ACTION GENOME 且从 VG 预训练加载时：只加载除分类头/关系头外的权重，然后按 AG 类别数重建并初始化两个头
  _C.MODEL.DETR.VG_PRETRAINED_FOR_AG = False

  # Object classification split heads (regular/small/fine/bg)
  _C.MODEL.OBJ_SPLIT = CN()
  _C.MODEL.OBJ_SPLIT.ENABLED = False
  _C.MODEL.OBJ_SPLIT.REGULAR_CLASSES = []
  _C.MODEL.OBJ_SPLIT.SMALL_SHARED_CLASSES = []
  # Fine groups as list-of-lists, e.g. [[1,2],[7,8,9]]
  _C.MODEL.OBJ_SPLIT.FINE_GROUPS = []
  # Optional names for fine groups; if empty, auto names are used.
  _C.MODEL.OBJ_SPLIT.FINE_GROUP_NAMES = []
  # Per fine-group upsample switches (same length as FINE_GROUPS)
  _C.MODEL.OBJ_SPLIT.FINE_GROUPS_USE_UPSAMPLE = []
  # Enable 2x upsample on small-shared branch.
  _C.MODEL.OBJ_SPLIT.SMALL_SHARED_USE_UPSAMPLE = False
  # Temperature scaling before assembling full logits.
  _C.MODEL.OBJ_SPLIT.USE_TEMP_SCALING = False
  # Auxiliary loss weights for split heads.
  _C.MODEL.OBJ_SPLIT.AUX_LOSS_WEIGHT_REG = 0.0
  _C.MODEL.OBJ_SPLIT.AUX_LOSS_WEIGHT_SMALL = 0.0
  _C.MODEL.OBJ_SPLIT.AUX_LOSS_WEIGHT_FINE = 0.0

  # ROI-guided refinement for small subject/object classification.
  _C.MODEL.ROI_REFINE = CN()
  _C.MODEL.ROI_REFINE.ENABLED = False
  _C.MODEL.ROI_REFINE.STRIDE = 14
  _C.MODEL.ROI_REFINE.POOL_SIZE = 7
  _C.MODEL.ROI_REFINE.SMALL_AREA_THRESH = 0.02
  _C.MODEL.ROI_REFINE.DETACH_BOXES = True
  _C.MODEL.ROI_REFINE.USE_GATE = True
  _C.MODEL.ROI_REFINE.LOSS_ENABLED = False
  _C.MODEL.ROI_REFINE.LOSS_WEIGHT = 1.0
  _C.MODEL.ROI_REFINE.APPLY_TO = "small_only"
  _C.MODEL.ROI_REFINE.ONLY_ROI_CLS = False

  _C.MODEL.DETR.HIDDEN_DIM = 256
  _C.MODEL.DETR.NUM_OBJECT_QUERIES = 10
  _C.MODEL.DETR.NUM_RELATION_QUERIES = 10
  _C.MODEL.DETR.CREATE_BG_PAIRS = False

  _C.SOLVER.OPTIMIZER = "ADAMW"
  _C.SOLVER.BACKBONE_MULTIPLIER = 0.1
  _C.SOLVER.RELATION_MULTIPLIER = 1.0
  _C.SOLVER.ENTITY_MULTIPLIER = 1.0
  _C.SOLVER.GATE_LR_MULTIPLIER = 5.0  # high multiplier for temporal gate to escape saddle point
  # 以 epoch 为主导的训练长度控制；若 >0，则用它和数据集长度推导 MAX_ITER
  _C.SOLVER.MAX_EPOCH = 1
  _C.SOLVER.MAX_TO_KEEP = 2
  _C.MODEL.DF_DETR = CN()
  _C.MODEL.DF_DETR.NUM_CLASSES = 80

  # SAM3 Backbone
  _C.MODEL.SAM3 = CN()
  _C.MODEL.SAM3.ENABLED = False
  _C.MODEL.SAM3.CHECKPOINT_PATH = ""
  _C.MODEL.SAM3.IMAGE_SIZE = 1008
  _C.MODEL.SAM3.FEATURE_DIM = 256
  _C.MODEL.SAM3.CHANNEL_REPEAT = 1
  _C.MODEL.SAM3.FREEZE = True
  # -1 表示不自动解冻；>=0 时，训练到该 iter 自动解冻 SAM3 backbone（需配合 FREEZE=True 使用）
  _C.MODEL.SAM3.UNFREEZE_AT_ITER = -1
  _C.MODEL.SAM3.DEVICE = "cuda"
  _C.MODEL.SAM3.USE_PRECOMPUTED = False
  _C.MODEL.SAM3.FEATUREMAP_DIR = "data/featuremaps"
  _C.MODEL.SAM3.TARGET_STRIDE = 32
  _C.MODEL.SAM3.USE_PATCH_MERGE = False
  _C.MODEL.SAM3.USE_FPN = False  # Enable FPN-style multi-scale features
  _C.MODEL.SAM3.FPN_STRIDES = [4, 8, 16, 32]  # Feature pyramid strides
  _C.MODEL.SAM3.USE_BACKBONE_FPN = True  # Prefer native SAM3 backbone_fpn levels
  _C.MODEL.SAM3.MULTISCALE_MERGE = "last"  # last | sum | concat

  # Temporal aggregation (two-state memory) before DETR transformer
  _C.MODEL.TEMPORAL = CN()
# Quality-aware auxiliary CE masking (default OFF)
  _C.MODEL.DETR.OBJ_MISSED_AUX = CN()
  _C.MODEL.DETR.OBJ_MISSED_AUX.ENABLED = False
  _C.MODEL.DETR.OBJ_MISSED_AUX.IOU_THRESH = 0.75
  _C.MODEL.DETR.OBJ_MISSED_AUX.IOU_THRESH_SUB = 0.75
  _C.MODEL.DETR.OBJ_MISSED_AUX.IOU_THRESH_OBJ = 0.85
  _C.MODEL.DETR.OBJ_MISSED_AUX.MIN_SCORE = 0.0
  _C.MODEL.DETR.OBJ_MISSED_AUX.MIN_SCORE_SUB = 0.0
  _C.MODEL.DETR.OBJ_MISSED_AUX.MIN_SCORE_OBJ = 0.0
  _C.MODEL.DETR.OBJ_MISSED_AUX.LOSS_WEIGHT = 0.2
  _C.MODEL.DETR.OBJ_MISSED_AUX.APPLY_SUBJECT = True
  _C.MODEL.DETR.OBJ_MISSED_AUX.APPLY_OBJECT = True
  _C.MODEL.DETR.OBJ_MISSED_AUX.START_ITER = 0
  _C.MODEL.DETR.OBJ_MISSED_AUX.DEBUG = False
  _C.MODEL.DETR.OBJ_MISSED_AUX.DISCOUNT_FACTOR = 0.0
  _C.MODEL.DETR.OBJ_MISSED_AUX.DISCOUNT_IOU_THRESH = 0.5
  _C.MODEL.DETR.OBJ_MISSED_AUX.TRIPLET_CONF_ALPHA = 0.0
  _C.MODEL.TEMPORAL.ENABLED = False
  _C.MODEL.TEMPORAL.EVAL_ENABLED = False
  # feature_ema (legacy) | object_query_memory_v1
  _C.MODEL.TEMPORAL.MODE = "feature_ema"
  _C.MODEL.TEMPORAL.ALPHA_INIT = 0.7
  _C.MODEL.TEMPORAL.NUM_MEMORY_SLOTS = 32
  _C.MODEL.TEMPORAL.MEMORY_TOPK = 16
  _C.MODEL.TEMPORAL.MEMORY_SCORE_THRESH = 0.5
  _C.MODEL.TEMPORAL.MEMORY_IOU_THRESH = 0.5
  _C.MODEL.TEMPORAL.MEMORY_MAX_MISS = 2
  # prediction: write high-confidence predictions; matched_gt: only write predictions matched to GT.
  _C.MODEL.TEMPORAL.MEMORY_UPDATE_MODE = "prediction"
  _C.MODEL.TEMPORAL.MEMORY_MATCH_IOU_THRESH = 0.5
  _C.MODEL.TEMPORAL.MEMORY_MATCH_REQUIRE_CLASS = True
  _C.MODEL.TEMPORAL.MEMORY_STORE_GT_BOXES = True
  _C.MODEL.TEMPORAL.DETACH_MEMORY = True
  _C.MODEL.TEMPORAL.INJECT_METHOD = "add_first_k"

  _C.MODEL.TEMPORAL.CACHE_DECAY = 0.85
  _C.MODEL.TEMPORAL.CACHE_MATCH_IOU = 0.5
  _C.MODEL.TEMPORAL.CACHE_MAX_AGE = 8
  _C.MODEL.TEMPORAL.CACHE_MAX_MISS = 2
  _C.MODEL.TEMPORAL.CACHE_MAX_SIZE = 32
  _C.MODEL.TEMPORAL.CACHE_MIN_SCORE = 0.2
  _C.MODEL.TEMPORAL.CACHE_RESET_ON_VIDEO_SWITCH = True
  _C.MODEL.TEMPORAL.CACHE_SCORE_THRESH = 0.5
  _C.MODEL.TEMPORAL.NON_KEY_RUN_OBJECT_ONLY = False
  _C.MODEL.TEMPORAL.RELATION_MEMORY_ENABLED = False  # also inject temporal memory into relation queries
  # object: relation queries read object memory; relation: use a dedicated relation memory bank.
  _C.MODEL.TEMPORAL.RELATION_MEMORY_SOURCE = "object"
  _C.MODEL.TEMPORAL.RELATION_MEMORY_UPDATE_MODE = "prediction"
  _C.MODEL.TEMPORAL.GATE_MIN = 0.0
  _C.MODEL.TEMPORAL.GATE_MAX = 1.0
  _C.MODEL.TEMPORAL.GATE_WARMUP_ITERS = 0
  _C.MODEL.TEMPORAL.RELATION_GATE_MIN = 0.0
  _C.MODEL.TEMPORAL.RELATION_GATE_MAX = 1.0
  _C.MODEL.TEMPORAL.RELATION_GATE_WARMUP_ITERS = 0
  _C.MODEL.TEMPORAL.NON_KEY_SKIP_EVAL = False
  _C.MODEL.TEMPORAL.NON_KEY_SKIP_LOSS = False
  _C.DATASETS.AG_TEMPORAL = CN()
  _C.DATASETS.AG_TEMPORAL.ENABLED = False
  _C.DATASETS.AG_TEMPORAL.NUM_INTERMEDIATE_FRAMES = 1
  _C.DATASETS.AG_TEMPORAL.CLIP_MODE = "between_keyframes"
  _C.DATASETS.AG_TEMPORAL.RETURN_CLIP = False

  # MODEL Variants 
  _C.MODEL.DF_DETR.WITH_BOX_REFINE = False
  _C.MODEL.DF_DETR.TWO_STAGE = False

  # Backbone
  _C.MODEL.DF_DETR.BACKBONE = "resnet50"
  _C.MODEL.DF_DETR.DILATION = False
  _C.MODEL.DF_DETR.POSITIONAL_EMBEDDING = 'sine'
  _C.MODEL.DF_DETR.NUM_FEATURE_LEVELS = 4

  # Transformer
  _C.MODEL.DF_DETR.ENC_LAYERS = 6
  _C.MODEL.DF_DETR.DEC_LAYERS = 6
  _C.MODEL.DF_DETR.DIM_FEEDFORWARD = 1024
  _C.MODEL.DF_DETR.HIDDEN_DIM = 256
  _C.MODEL.DF_DETR.DROPOUT = 0.1
  _C.MODEL.DF_DETR.NHEADS = 8
  _C.MODEL.DF_DETR.NUM_OBJECT_QUERIES = 10
  _C.MODEL.DETR.DEC_N_POINTS = 4
  _C.MODEL.DETR.ENC_N_POINTS = 4

  # Mathcher
  _C.MODEL.DF_DETR.SET_COST_CLASS = 2
  _C.MODEL.DF_DETR.SET_COST_BBOX = 5
  _C.MODEL.DF_DETR.SET_COST_GIOU = 2

  # Loss 
  _C.MODEL.DF_DETR.CLS_LOSS_WEIGHT = 2.
  _C.MODEL.DF_DETR.BBOX_LOSS_WEIGHT = 5.
  _C.MODEL.DF_DETR.GIOU_LOSS_WEIGHT = 2.
  _C.MODEL.DF_DETR.RELATION_LOSS_WEIGHT = 1.
  _C.MODEL.DF_DETR.FOCAL_ALPHA = 0.25
  _C.MODEL.DF_DETR.DEEP_SUPERVISION = True

  # relation part
  _C.MODEL.DF_DETR.RELATION_DEC_LAYERS = 4
  _C.MODEL.DF_DETR.PRE_NORM = False
  _C.MODEL.DF_DETR.RELATION_HEAD = True

  # custom configs
  _C.MODEL.DETR.ONE_TO_MANY = False

  # o2m
  _C.MODEL.DETR.ONE2MANY_SCHEME = 'static'
  _C.MODEL.DETR.ONE2MANY_DYNAMIC_SCHEME = 'min'
  _C.MODEL.DETR.ONE2MANY_K = 1
  _C.MODEL.DETR.MATCH_INDEPENDENT = False
  _C.MODEL.DETR.ONE2MANY_PREDICATE_SCORE = False
  _C.MODEL.DETR.ONE2MANY_PREDICATE_WEIGHT = 1.0

  # grouping
  _C.MODEL.DETR.MULTIPLY_QUERY = 1
  _C.MODEL.DETR.USE_GROUP_MASK = False
  _C.MODEL.DETR.ONLY_PREDICATE_MULTIPLY = False
  _C.MODEL.DETR.NUM_GROUPS = 5

  # wandb
  _C.WANDB = CN()
  _C.WANDB.USE_WANDB = False
  _C.WANDB.ENTITY = 'your_entity'
  _C.WANDB.PROJECT = 'speaq'
  _C.WANDB.GROUP = 'speaq'
  _C.WANDB.EXP_NAME = 'default_exp_name'


def add_scenegraph_config(cfg):
    _C = cfg
    
    _C.GLOVE_DIR = 'glove/'
    _C.DEV_RUN = False
    ###################################################################################################

    _C.MODEL.SCENEGRAPH_ON = True
    _C.MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = True
    _C.MODEL.USE_MASK_ON_NODE = False
    _C.MODEL.ROI_HEADS.OBJECTNESS_THRESH = 0.3
    _C.MODEL.GROUP_NORM = CN()
    _C.MODEL.GROUP_NORM.DIM_PER_GP = -1
    _C.MODEL.GROUP_NORM.NUM_GROUPS = 32
    _C.MODEL.GROUP_NORM.EPSILON = 1e-5 # default: 1e-5
    ###################################################################################################
    _C.MODEL.ROI_SCENEGRAPH_HEAD = CN()
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NAME = 'SceneGraphHead'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MODE = 'predcls'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.REQUIRE_BOX_OVERLAP = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NUM_SAMPLE_PER_GT_REL = 4  # when sample fg relationship from gt, the max number of corresponding proposal pairs
    _C.MODEL.ROI_SCENEGRAPH_HEAD.BATCH_SIZE_PER_IMAGE = 64
    _C.MODEL.ROI_SCENEGRAPH_HEAD.POSITIVE_FRACTION = 0.25
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_GT_BOX = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_GT_OBJECT_LABEL = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NMS_FILTER_DUPLICATES = True
    
    _C.MODEL.SCENEGRAPH_SAMPLER = CN()
    _C.MODEL.SCENEGRAPH_SAMPLER.NAME = "TransformerRelationSampler"

    _C.MODEL.SCENEGRAPH_LOSS = CN()
    _C.MODEL.SCENEGRAPH_LOSS.NAME = "TransformerRelatonLoss"

    _C.MODEL.SCENEGRAPH_POST_PROCESSOR = CN()
    _C.MODEL.SCENEGRAPH_POST_PROCESSOR.NAME = 'TransformerRelationPostProcesser'

    _C.MODEL.ROI_SCENEGRAPH_HEAD.RETURN_SEG_MASKS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.RETURN_SEG_ANNOS = False

    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_VISION = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_BIAS = True
    
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_MASK_ATTENTION = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MASK_ATTENTION_TYPE = 'Self'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.SIGMOID_ATTENTION = True

    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICTOR = "MotifPredictor"
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NUM_CLASSES = 50
    _C.MODEL.ROI_SCENEGRAPH_HEAD.EMBED_DIM = 200
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_DROPOUT_RATE = 0.2
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_HIDDEN_DIM = 512
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_POOLING_DIM = 4096
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_OBJ_LAYER = 1  # assert >= 1
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_REL_LAYER = 1  # assert >= 1
    _C.MODEL.ROI_SCENEGRAPH_HEAD.ADD_GTBOX_TO_PROPOSAL_IN_TRAIN = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.SEG_BBOX_LOSS_MULTIPLIER = 1.0
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_ONLY_FG_PROPOSALS = True

    _C.MODEL.ROI_SCENEGRAPH_HEAD.LABEL_SMOOTHING_LOSS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.REL_PROP = [0.01858, 0.00057, 0.00051, 0.00109, 0.00150, 0.00489, 0.00432, 0.02913, 0.00245, 0.00121, 
                                       0.00404, 0.00110, 0.00132, 0.00172, 0.00005, 0.00242, 0.00050, 0.00048, 0.00208, 0.15608,
                                       0.02650, 0.06091, 0.00900, 0.00183, 0.00225, 0.00090, 0.00028, 0.00077, 0.04844, 0.08645,
                                       0.31621, 0.00088, 0.00301, 0.00042, 0.00186, 0.00100, 0.00027, 0.01012, 0.00010, 0.01286,
                                       0.00647, 0.00084, 0.01077, 0.00132, 0.00069, 0.00376, 0.00214, 0.11424, 0.01205, 0.02958]

    _C.MODEL.ROI_SCENEGRAPH_HEAD.ZERO_SHOT_TRIPLETS = 'evaluation/datasets/vg/zeroshot_triplet.pytorch'

    #TransformerContext
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER = CN()
    # for TransformerPredictor only
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.DROPOUT_RATE = 0.1   
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.OBJ_LAYER = 4        
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.REL_LAYER = 2        
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.NUM_HEAD = 8         
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.INNER_DIM = 2048     
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.KEY_DIM = 64         
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.VAL_DIM = 64     
    ###################################################################################################
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS = CN()
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.NAME = 'BoxFeatureExtractor'
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_RESOLUTION = 28
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_TYPE = 'ROIAlignV2'
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.BOX_FEATURE_MASK = True 
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.CLASS_LOGITS_WITH_MASK = False

    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS = CN()
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.NAME = 'RelationFeatureExtractor'
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.USE_MASK_COMBINER = False
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.MULTIPLY_LOGITS_WITH_MASKS = True

    # Overlap threshold for an RoI to be considered foreground (if >= FG_IOU_THRESHOLD)
    _C.MODEL.ROI_HEADS.FG_IOU_THRESHOLD = 0.5
    _C.MODEL.ROI_HEADS.REFINE_SEG_MASKS = True
    _C.MODEL.ROI_HEADS.SEGMENTATION_STEP_MASK_REFINE = True

    # Settings for relation testing
    _C.TEST.RELATION = CN()
    _C.TEST.RELATION.REQUIRE_OVERLAP = True
    _C.TEST.RELATION.LATER_NMS_PREDICTION_THRES = 0.3 
    _C.TEST.RELATION.MULTIPLE_PREDS = False
    _C.TEST.RELATION.IOU_THRESHOLD = 0.5


    _C.DATASETS.VISUAL_GENOME.CLIPPED = False
    
    #############################
    _C.TEST.NUM_REL = 1
    _C.TEST.PNMS = False