#!/usr/bin/env bash
# Debug: eval checkpoint first, then train with frequent eval to detect degradation
set -euo pipefail
PROJ=/home/cfs/shizekun1_v/sam3-sgg-Auxiliary-Matching
cd "$PROJ"
CKPT_DIR=z_outputs/fulltask_temporal_roi_no_xsam_bs96_iter40000
CKPT="${CKPT_DIR}/model_0024999.pth"
DEBUG_OUT="${CKPT_DIR}/debug_loadweight"
mkdir -p "${DEBUG_OUT}"

echo "=============================================="
echo "[DEBUG] Step 1: eval-only with ${CKPT}"
echo "=============================================="
python3 train_iterative_model.py     --eval-only     --num-gpus 8     --config-file configs/speaq_ag_roi.yaml     --dist-url tcp://127.0.0.1:29500     OUTPUT_DIR "${DEBUG_OUT}"     DATASETS.ACTION_GENOME.ANNOTATIONS dataset/annotations     DATASETS.ACTION_GENOME.FRAMES dataset/frames     DATASETS.ACTION_GENOME.NUM_VIDEOS_TRAIN -1     MODEL.SAM3.ENABLED True     MODEL.SAM3.CHECKPOINT_PATH sam3/weights/sam3.pt     MODEL.SAM3.FREEZE True     MODEL.SAM3.USE_PATCH_MERGE False     MODEL.ROI_REFINE.ENABLED True     MODEL.ROI_REFINE.LOSS_ENABLED True     MODEL.TEMPORAL.ENABLED True     MODEL.TEMPORAL.EVAL_ENABLED True     MODEL.TEMPORAL.MODE object_query_memory_v1     MODEL.TEMPORAL.RELATION_MEMORY_ENABLED True     MODEL.TEMPORAL.RELATION_MEMORY_SOURCE relation     MODEL.TEMPORAL.MEMORY_UPDATE_MODE matched_gt     MODEL.TEMPORAL.RELATION_MEMORY_UPDATE_MODE matched_gt     MODEL.TEMPORAL.GATE_MIN 0.0     MODEL.TEMPORAL.GATE_MAX 0.20     MODEL.TEMPORAL.GATE_WARMUP_ITERS 600     MODEL.TEMPORAL.RELATION_GATE_MIN 0.0     MODEL.TEMPORAL.RELATION_GATE_MAX 0.10     MODEL.TEMPORAL.RELATION_GATE_WARMUP_ITERS 1000     MODEL.DETR.BOX_LOSS_TYPE giou     MODEL.DETR.USE_CORNER_LOSS False     MODEL.DETR.PERSON_SCORE_SCALE 1.0     MODEL.WEIGHTS "${CKPT}"     MODEL.DETR.HEAD_WEIGHTS "${CKPT}"     MODEL.DETR.LOAD_HEAD_ONLY False     MODEL.DETR.LOAD_FULL_WEIGHTS True     SOLVER.IMS_PER_BATCH 96     SOLVER.BASE_LR 0.0008     SOLVER.MAX_ITER 3000     SOLVER.STEPS '(1000,2000)'     SOLVER.WARMUP_ITERS 1200     TEST.EVAL_PERIOD 100     DATALOADER.NUM_WORKERS 4     2>&1 | tee "${DEBUG_OUT}/eval_only.log"
echo "[DEBUG] Step 1 done"

echo ""
echo "=============================================="
echo "[DEBUG] Step 2: train 3000 iter, eval every 1000"
echo "=============================================="
python3 train_iterative_model.py     --num-gpus 8     --config-file configs/speaq_ag_roi.yaml     --dist-url tcp://127.0.0.1:29500     OUTPUT_DIR "${DEBUG_OUT}"     DATASETS.ACTION_GENOME.ANNOTATIONS dataset/annotations     DATASETS.ACTION_GENOME.FRAMES dataset/frames     DATASETS.ACTION_GENOME.NUM_VIDEOS_TRAIN -1     MODEL.SAM3.ENABLED True     MODEL.SAM3.CHECKPOINT_PATH sam3/weights/sam3.pt     MODEL.SAM3.FREEZE True     MODEL.SAM3.USE_PATCH_MERGE False     MODEL.ROI_REFINE.ENABLED True     MODEL.ROI_REFINE.LOSS_ENABLED True     MODEL.TEMPORAL.ENABLED True     MODEL.TEMPORAL.EVAL_ENABLED True     MODEL.TEMPORAL.MODE object_query_memory_v1     MODEL.TEMPORAL.RELATION_MEMORY_ENABLED True     MODEL.TEMPORAL.RELATION_MEMORY_SOURCE relation     MODEL.TEMPORAL.MEMORY_UPDATE_MODE matched_gt     MODEL.TEMPORAL.RELATION_MEMORY_UPDATE_MODE matched_gt     MODEL.TEMPORAL.GATE_MIN 0.0     MODEL.TEMPORAL.GATE_MAX 0.20     MODEL.TEMPORAL.GATE_WARMUP_ITERS 600     MODEL.TEMPORAL.RELATION_GATE_MIN 0.0     MODEL.TEMPORAL.RELATION_GATE_MAX 0.10     MODEL.TEMPORAL.RELATION_GATE_WARMUP_ITERS 1000     MODEL.DETR.BOX_LOSS_TYPE giou     MODEL.DETR.USE_CORNER_LOSS False     MODEL.DETR.PERSON_SCORE_SCALE 1.0     MODEL.WEIGHTS "${CKPT}"     MODEL.DETR.HEAD_WEIGHTS "${CKPT}"     MODEL.DETR.LOAD_HEAD_ONLY False     MODEL.DETR.LOAD_FULL_WEIGHTS True     SOLVER.IMS_PER_BATCH 96     SOLVER.BASE_LR 0.0008     SOLVER.MAX_ITER 3000     SOLVER.STEPS '(1000,2000)'     SOLVER.WARMUP_ITERS 200     SOLVER.CHECKPOINT_PERIOD 1000     SOLVER.GATE_LR_MULTIPLIER 5.0     TEST.EVAL_PERIOD 1000     DATALOADER.NUM_WORKERS 4     2>&1 | tee "${DEBUG_OUT}/train_3k.log"
echo "[DEBUG] Step 2 done. Results in ${DEBUG_OUT}/"
