#!/usr/bin/env bash
# Full task v3-only (no v2, no ROI), 4 GPU DDP, eval every 10000
set -euo pipefail
PROJ=/home/cfs/shizekun1_v/sam3-sgg-Auxiliary-Matching
cd "$PROJ"
OUTPUT_DIR="${1:-z_outputs/fulltask_v3_only_bs48_iter40000}"
NUM_GPUS="${2:-4}"
mkdir -p "${OUTPUT_DIR}"
export ROI_GATE_LOG_PATH="${OUTPUT_DIR}/roi_gate_log.csv"
echo "[Full v3-Only] OUTPUT=${OUTPUT_DIR} GPU=${NUM_GPUS}"

python3 train_iterative_model.py     --num-gpus "${NUM_GPUS}"     --config-file configs/speaq_actiongenome_minimal.yaml     --dist-url tcp://127.0.0.1:29700     OUTPUT_DIR "${OUTPUT_DIR}"     DATASETS.ACTION_GENOME.ANNOTATIONS dataset/annotations     DATASETS.ACTION_GENOME.FRAMES dataset/frames     DATASETS.ACTION_GENOME.NUM_VIDEOS_TRAIN -1     MODEL.WEIGHTS model_0099999.pth     MODEL.DETR.HEAD_WEIGHTS model_0099999.pth     MODEL.DETR.LOAD_HEAD_ONLY False     MODEL.DETR.LOAD_FULL_WEIGHTS True     MODEL.DETR.LOAD_CLASS_HEAD True     MODEL.SAM3.ENABLED True     MODEL.SAM3.CHECKPOINT_PATH sam3/weights/sam3.pt     MODEL.SAM3.FREEZE True     MODEL.SAM3.USE_PATCH_MERGE False     MODEL.TEMPORAL.ENABLED True     MODEL.TEMPORAL.EVAL_ENABLED True     MODEL.TEMPORAL.MODE triplet_memory_v3     MODEL.TEMPORAL.TRIPLET_MEMORY_ENABLED True     MODEL.TEMPORAL.INJECT_OBJECT True     MODEL.TEMPORAL.INJECT_RELATION True     MODEL.TEMPORAL.NON_KEY_SKIP_LOSS True     MODEL.TEMPORAL.NON_KEY_SKIP_EVAL True     MODEL.TEMPORAL.NON_KEY_RUN_OBJECT_ONLY True     MODEL.ROI_REFINE.ENABLED False     MODEL.ROI_REFINE.LOSS_ENABLED False     SOLVER.IMS_PER_BATCH 48     SOLVER.BASE_LR 0.0004     SOLVER.MAX_ITER 40000     SOLVER.STEPS '(8000,32000)'     SOLVER.WARMUP_ITERS 2000     SOLVER.CHECKPOINT_PERIOD 5000     TEST.EVAL_PERIOD 5000     SOLVER.EVAL_FIRST True     DATALOADER.NUM_WORKERS 4

RET=$?
echo "[Full v3-Only] Done exit=${RET}"
